# Generated by Django 3.2.25 on 2025-06-25 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='lead',
            name='status',
        ),
        migrations.AddField(
            model_name='lead',
            name='statuses',
            field=models.ManyToManyField(related_name='leads', to='leads.Status'),
        ),
    ]
