# Generated by Django 3.2.25 on 2025-06-26 00:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0002_auto_20250625_2256'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(max_length=50)),
                ('message', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='lead',
            name='called_at',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='follow_up',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='next_call_at',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='statuses',
        ),
        migrations.AddField(
            model_name='lead',
            name='phone_number',
            field=models.CharField(default=1234567890, max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lead',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('prospect', 'Prospect'), ('interested', 'Interested'), ('customer', 'Customer')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='lead',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.DeleteModel(
            name='CallLog',
        ),
        migrations.DeleteModel(
            name='Status',
        ),
        migrations.AddField(
            model_name='chathistory',
            name='lead',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_histories', to='leads.lead'),
        ),
    ]
